[[place]]

Name = "jinno"
Title = "旧陣之尾橋跡"
PlaceCategory = "HISTORY"
BgPath = "./images/bg/normalize/pattern_a.png"
KeyPath = "./images/key/normalize/jinno.png"
Descs = ["折口川に架かっていた橋の跡。", "橋台が残っている。"]
Location = "鹿児島県阿久根市折口"

[[place]]

Name = "nabeishi"
Title = "鍋石"
PlaceCategory = "HISTORY"
BgPath = "./images/bg/normalize/pattern_b.png"
KeyPath = "./images/key/normalize/nabeishi.png"
Descs = ["阿久根の七不思議の1つ。", "鍋の形をした岩。"]
Location = "鹿児島県阿久根市折口"

[[place]]

Name = "r499"
Title = "国道499号線"
PlaceCategory = "SCENIC"
BgPath = "./images/bg/normalize/pattern_c.png"
KeyPath = "./images/key/normalize/r499.png"
Descs = ["阿久根市内の陸上区間はわずか62m", "しかない国道。", "市内で唯一の2車線道路区間。"]
Location = "鹿児島県阿久根市栄町"

[[place]]

Name = "okawa"
Title = "旧尻無トンネル"
PlaceCategory = "HISTORY"
BgPath = "./images/bg/normalize/pattern_d.png"
KeyPath = "./images/key/normalize/okawa.png"
Descs = ["鉄道トンネル跡。", "両側の封鎖で入ることはできない。"]
Location = "鹿児島県阿久根市大川"