name: ⚗️Check

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.23'
      - name: remove
        run: |
          rm ./images/bg/normalize/*
          rm ./images/key/normalize/*
          rm ./images/card/*
      - name: exec
        run: |
          go run . normalizeBg
          go run . normalizeKey
          go run . build
      - name: check diff
        run: git diff --exit-code

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.23'
      - name: build
        run: go build .
      - name: test
        run: go test -v
